name: Kintone Deploy to Test environment
on:
  push:
    branches:
      - test
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: test-deploy-group
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run deploy-test
        env:
          KINTONE_BASE_URL: ${{ secrets.KINTONE_BASE_URL }}
          KINTONE_USER: ${{ secrets.KINTONE_USER }}
          KINTONE_PASSWORD: ${{ secrets.KINTONE_PASSWORD }}
